EF core, Postgres, Value Objects
IDerter/Pet-Search pull request #5
Opened 2024-08-14 14:02 UTC by IDerter

Add ef core postgresq in docker compose, configuration all domain models. Add LoggerFactory and made migrations with table-names in snake_case style. Add Entity abstract class.

2024-08-15 07:41 UTC, KirillSachkov requested changes

2024-08-15 07:41 UTC, KirillSachkov commented on backend/src/Pet-Search.API/Program.cs
> +	options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection"));
Конфигурацию нужно делать внутри контекста, как я показывал

2024-08-15 07:41 UTC, KirillSachkov commented on backend/src/Pet-Search.Domain/Entities/VolunteerContext/Volunteer.cs
> +	public RequisiteList? RequisiteList { get; private set; }
лишние отступы

2024-08-15 07:41 UTC, KirillSachkov commented on backend/src/Pet-Search.Domain/Entities/VolunteerContext/Volunteer.cs
> +    public List<SocialNetwork> SocialNetworks { get; private set; } = [];
социальные сети сделай также, как и реквизиты

2024-08-15 07:41 UTC, KirillSachkov commented on backend/src/Pet-Search.Domain/ValueObjects/VolunteerVO/FullName.cs
> +
лишние пробелы

2024-08-15 07:41 UTC, KirillSachkov commented on backend/src/Pet-Search.Infrastructure/ApplicationDbContext.cs
> +        LoggerFactory.Create(builder => { builder.AddConsole(); });
здесь нужен отступ

2024-08-15 07:41 UTC, KirillSachkov commented on backend/src/Pet-Search.Infrastructure/ApplicationDbContext.cs
> +    public DbSet<Pet> Pets { get; set; }
DbSet для животных не нужен

2024-08-15 07:41 UTC, KirillSachkov commented on backend/src/Pet-Search.Infrastructure/Configurations/PetConfiguration.cs
> +				.IsRequired()
Неверные отступы, чаще использу ctrl + K + D

2024-08-15 07:41 UTC, KirillSachkov commented on backend/src/Pet-Search.Infrastructure/Configurations/VolunteerConfiguration.cs
> +				.HasMaxLength(Constants.MAX_LOW_LENGTH);
Неправильные отступы

2024-08-16 07:32 UTC, IDerter commented on backend/src/Pet-Search.Infrastructure/ApplicationDbContext.cs
> +    public DbSet<Pet> Pets { get; set; }
А почему DbSet не нужен?

2024-08-16 07:42 UTC, KirillSachkov approved these changes

2024-08-16 09:34 UTC, merged